### PR TITLE
Drop Django 1.11 and Python 2.7

### PR DESCRIPTION
**Pull request by djw**
Both have been EOL'd.

### CODE REVIEW

**Comment by side2k** [comment]
Do we really need to drop support for python 2? Do we get any value from that?

**Comment by djw** [comment]
@side2k Why would we maintain support when neither Django 1.11 or Python 2 is supported anymore?

**Comment by side2k** [comment]
> @side2k Why would we maintain support when neither Django 1.11 or Python 2 is supported anymore?

because it doesn't seem to cost us much and there may be people who use this lib?

**Comment by djw** [comment]
@side2k When would be an appropriate time to drop support?

**Comment by side2k** [comment]
> @side2k When would be an appropriate time to drop support?

When the costs increase, I think.
Well, its all just pure theory, of course. Its not a blocker, just a thought. Feel free to ignore it 8)

**Comment by djw** [comment]
@side2k I intentionally maintained support until the Aggregator feature was merged, just in case anyone needs it, but now it's time to modernise!

**Review by side2k — APPROVED** [review]

**Pull request merged**
